# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialise.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

#### 1. Import the numpy package under the name `np` (★☆☆)

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [3]:
print(np.__version__)

np.show_config()

1.24.4
openblas64__info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['openblas\\lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['openblas\\lib']
blas_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['openblas\\lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['openblas\\lib']
openblas64__lapack_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['openblas\\lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None), ('HAVE_LAPACKE', None)]
    runtime_library_dirs = ['openblas\\lib']
lapack_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['openblas\\lib']
    language = c
    define_macros = [('HAVE_CBLAS', None

#### 3. Create a null vector of size 10 (★☆☆)

In [4]:
Z=np.zeros(10)
print(Z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. How to find the memory size of any array (★☆☆)

In [5]:
Z=np.zeros((10,10))

print("%d byte" %(Z.size*Z.itemsize))
print(Z.nbytes)

800 byte
800


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [6]:
#%run `python -c "import numpy; numpy.info(numpy.add)"`
#%run用来执行一个外部 Python 文件或者命令。
#反引号里的内容会当作 系统 shell 命令执行，并把结果返回。
#-c 参数表示 执行一段字符串形式的 Python 代码。


#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [7]:
Z=np.zeros(10)
Z[4]=1
print(Z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [8]:
Z=np.arange(10,50)
print(Z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [9]:
Z=np.arange(10,50)
Z=Z[::-1] #seq[start:stop:step]
print(Z)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [10]:
Z=np.arange(0,9).reshape(3,3)
print(Z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [11]:
nz=np.nonzero([1,2,0,0,4,0])
print(nz)

(array([0, 1, 4], dtype=int64),)


#### 11. Create a 3x3 identity matrix (★☆☆)

In [12]:
Z=np.eye(3)
print(Z)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [13]:
Z=np.random.random((3,3,3))
print(Z)

[[[0.27209028 0.50076576 0.30903277]
  [0.15860831 0.46066866 0.89829014]
  [0.1927483  0.68902243 0.87826556]]

 [[0.49034616 0.41068832 0.35811825]
  [0.11343989 0.66363774 0.27541757]
  [0.42085182 0.10049484 0.18055008]]

 [[0.42412248 0.87622983 0.08676064]
  [0.12610057 0.54154614 0.03548365]
  [0.64196036 0.40189735 0.94099904]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [14]:
Z=np.random.random((10,10))
print(Z.min(),Z.max())

0.019260167594054245 0.9794939852031386


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [15]:
Z=np.random.random(30)
print(Z.mean())

0.43273762199865773


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [16]:
Z=np.ones((10,10))
print(Z)
print('\n')
Z[1:-1,1:-1]=0
print(Z)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [17]:
Z=np.ones((10,10))
Z=np.pad(Z,pad_width=1,mode='constant',constant_values=0)
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [18]:
print(0*np.nan) #nan 
print(np.nan==np.nan) #False
print(np.inf>np.nan) #Fasle
print(np.nan-np.nan) #nan
print(np.nan in set([np.nan])) #True
print(0.3==3*0.1) #False

nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [19]:
Z=np.diag(1+np.arange(4),-1)  #-1代表对角线的下面一位
print(Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [20]:
Z = np.zeros((8,8),dtype=int)
Z[1::2,::2] = 1
Z[::2,1::2] = 1
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [21]:
print(np.unravel_index(99,(6,7,8)))

(1, 5, 3)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [22]:
Z=np.tile([[1,2],[3,4]],(4,4))  #(4,4) 行重复四次，列重复四次
print(Z)

[[1 2 1 2 1 2 1 2]
 [3 4 3 4 3 4 3 4]
 [1 2 1 2 1 2 1 2]
 [3 4 3 4 3 4 3 4]
 [1 2 1 2 1 2 1 2]
 [3 4 3 4 3 4 3 4]
 [1 2 1 2 1 2 1 2]
 [3 4 3 4 3 4 3 4]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [23]:
#全局标准化
Z=np.random.random((5,5))
Z=(Z-np.mean(Z))/np.std(Z)
print(Z)
#layer normal
Z=np.random.random((5,5))
Z=(Z-np.mean(Z,axis=1,keepdims=True))/np.mean(Z,axis=1,keepdims=True)
print(Z)

[[ 1.0352936   0.90271619 -1.06836785  0.40849751 -1.17464675]
 [ 0.27583158  1.18858708  0.46828374 -0.15013667  0.5558881 ]
 [-0.50627347  0.98571203 -1.19981754  1.03385863 -0.00652079]
 [-2.25307326  0.13356719  0.22231641 -1.1726351  -0.18688304]
 [ 0.74400914 -2.30993444  1.06912362 -0.02615451  1.03075861]]
[[-0.01327841  0.26883571 -0.34909652  0.26519127 -0.17165204]
 [ 1.33007796 -0.47241076  0.69852556 -0.72510682 -0.83108595]
 [-0.80998754 -0.74214044  1.07209112 -0.17352668  0.65356355]
 [-0.32557574  0.1568634   0.00648999  0.160833    0.00138935]
 [ 0.01585341  0.62504311 -0.84494352  0.38800625 -0.18395924]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [24]:
color=np.dtype([
    ("r",np.ubyte),
    ("g",np.ubyte),
    ("b",np.ubyte),
    ("a",np.ubyte)
])
# 定义一个 RGBA 颜色数组
pixels = np.array([
    (255, 0, 0, 255),     # 红色
    (0, 255, 0, 255),     # 绿色
    (0, 0, 255, 255),     # 蓝色
], dtype=color)
print(pixels)
print(pixels["r"])

[(255,   0,   0, 255) (  0, 255,   0, 255) (  0,   0, 255, 255)]
[255   0   0]


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [25]:
X=np.random.random((5,3))
Y=np.random.random((3,2))
Z=X@Y
print(Z)

[[0.468065   0.92009299]
 [0.60824527 0.56212434]
 [0.45381579 0.57601404]
 [0.36110205 0.61495883]
 [0.31989619 0.56953153]]

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [26]:
Z = np.arange(11)
Z[(3 < Z) & (Z < 8)] *= -1
print(Z)

[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [27]:
print(sum(range(5),-1))  # sum range(5)-1
#from numpy import *
print(sum(range(5),-1)) # -1代表axis

9
9


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [28]:
Z=np.arange(4)
print(Z**Z)
print(2<<Z>>2)
print(Z<-Z)
print(1j*Z) #虚数单位
print(Z/1/1)#返回浮点数
#print(Z<Z>Z) #Python 不允许连续三个操作符这样写，语法错误。

[ 1  1  4 27]
[0 1 2 4]
[False False False False]
[0.+0.j 0.+1.j 0.+2.j 0.+3.j]
[0. 1. 2. 3.]


#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [29]:
# print(np.array(0)/np.array(0))  #nan
# print(np.array(0)//np.array(0)) #报错: ZeroDivisionError
# np.array([np.nan]).astype(int).astype(float) # 输出: [-9223372036854775808.]


#### 29. How to round away from zero a float array ? (★☆☆)

In [30]:
Z = np.random.uniform(-10,+10,10)
print(Z)
print(np.copysign(np.ceil(np.abs(Z)), Z)) #numpy.copysign(x1, x2) 的作用是：数值部分取自x1，符号取自x2。
 
# More readable but less efficient
print(np.where(Z>0, np.ceil(Z), np.floor(Z)))

[ 2.63335452  4.95344187 -9.54164882  3.44917506  5.11141043 -9.10196903
  2.90682922 -4.59315254 -1.71864713 -0.37139155]
[  3.   5. -10.   4.   6. -10.   3.  -5.  -2.  -1.]
[  3.   5. -10.   4.   6. -10.   3.  -5.  -2.  -1.]


#### 30. How to find common values between two arrays? (★☆☆)

In [31]:
A=np.random.randint(0,10,10)
B=np.random.randint(0,10,10)
print(A,B)
print(np.intersect1d(A,B))

[3 6 1 4 0 8 7 0 1 3] [6 5 9 4 8 0 9 9 0 7]
[0 4 6 7 8]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [32]:
print(np.sqrt(-1))  #invaild
print(np.emath.sqrt(-1))  #1j
print(np.sqrt(-1)==np.emath.sqrt(-1))

nan
1j
False


C:\Users\86183\AppData\Local\Temp\ipykernel_6600\1276047865.py:1: RuntimeWarning: invalid value encountered in sqrt
  print(np.sqrt(-1))  #invaild
C:\Users\86183\AppData\Local\Temp\ipykernel_6600\1276047865.py:3: RuntimeWarning: invalid value encountered in sqrt
  print(np.sqrt(-1)==np.emath.sqrt(-1))


#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [33]:
print(np.datetime64('today')-np.timedelta64(1))
print(np.datetime64('today'))
print(np.datetime64('today')+np.timedelta64(10))

2025-09-27
2025-09-28
2025-10-08


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [34]:
Z=np.arange("2016-07",'2016-08',dtype="datetime64[D]")
print(Z)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [35]:
A=np.ones(3)*1
B=np.ones(3)*2
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)
print(A)

[-1.5 -1.5 -1.5]


#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [36]:
Z=np.random.uniform(0,10,10)
print(Z)
print(Z-Z%1)
print(Z//1)
print(np.floor(Z))
print(Z.astype(int))
print(np.trunc(Z))

[8.20569952 0.3259993  9.55974825 2.86538027 4.38751368 8.4683926
 7.43352636 3.29160819 2.15312748 3.76990332]
[8. 0. 9. 2. 4. 8. 7. 3. 2. 3.]
[8. 0. 9. 2. 4. 8. 7. 3. 2. 3.]
[8. 0. 9. 2. 4. 8. 7. 3. 2. 3.]
[8 0 9 2 4 8 7 3 2 3]
[8. 0. 9. 2. 4. 8. 7. 3. 2. 3.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [37]:
Z=np.zeros((5,5))
Z+=np.arange(0,5)
print(Z)

Z=np.tile(np.arange(0,5),(5,1))
print(Z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]
[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [38]:
def generate():
    for x in range(10):
        yield x
Z=np.fromiter(generate(),dtype=float,count=-1)  # count=-1 默认行为，读完整个迭代器 
print(Z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [39]:
print(np.linspace(0,1,11,endpoint=False)[1:])  #endpoint=False 不包括最后那个1

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [40]:
Z=np.random.random(10)
print(Z)
Z.sort()
print(Z)

[0.55068147 0.55034203 0.46520525 0.38334405 0.883298   0.61143337
 0.63235152 0.97978102 0.26282989 0.90920212]
[0.26282989 0.38334405 0.46520525 0.55034203 0.55068147 0.61143337
 0.63235152 0.883298   0.90920212 0.97978102]


#### 41. How to sum a small array faster than np.sum? (★★☆)

In [41]:
Z=np.arange(10)
print(Z.sum())
print(np.add.reduce(Z))

45
45


#### 42. Consider two random arrays A and B, check if they are equal (★★☆)

In [42]:
A=np.random.randint(0,2,5)
B=np.random.randint(0,2,5)
print(A)
print(B)
equal=np.allclose(A,B)
print(equal)

equal=np.array_equal(A,B)
print(equal)

[0 0 1 1 1]
[1 1 0 1 1]
False
False


#### 43. Make an array immutable (read-only) (★★☆)

In [43]:
Z=np.ones(10)
Z.flags.writeable=False
Z[0]=1
print(Z)

ValueError: assignment destination is read-only

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [ ]:
Z=np.random.random((10,2))
X,Y=Z[:,0],Z[:,1]
R=np.sqrt(X**2+Y**2)
T=np.arctan2(Y,X)
print(R)
print(T)

[1.1620089  0.98712866 0.52844241 0.43708483 0.81544971 0.45342672
 0.76742457 1.13368848 0.6647307  0.60319366]
[0.61388473 1.54298316 0.60788997 0.99901019 1.36913833 1.28254565
 1.26550322 0.7136258  1.37430429 1.00637177]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [ ]:
Z=np.random.random(10)
print(Z)
Z[Z.argmax()]=0
print(Z)

[0.97579524 0.83874792 0.41607974 0.08610707 0.29951703 0.77562928
 0.14105617 0.42359033 0.21693529 0.47174943]
[0.         0.83874792 0.41607974 0.08610707 0.29951703 0.77562928
 0.14105617 0.42359033 0.21693529 0.47174943]


#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [ ]:
Z = np.zeros((5,5), [('x',float),('y',float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,5),
                             np.linspace(0,1,5))
print(Z)


[[(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)]
 [(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)]
 [(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)]
 [(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)]
 [(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)]]
[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

In [ ]:
X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)  # M[i,j]=X[i]-Y[j]
print(np.linalg.det(C))

3638.163637117973


#### 48. Print the minimum and maximum representable values for each numpy scalar type (★★☆)

In [ ]:
for type in [np.int8,np.int32,np.int64]:
    print(np.iinfo(type).min)
    print(np.iinfo(type).max)
for type in (np.float32,np.float64):
    print(np.finfo(type).min)
    print(np.finfo(type).max)
    print(np.finfo(type).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆)

In [ ]:
np.set_printoptions(threshold=float('inf'))
Z=np.zeros((40,40))
print(Z)
# np.set_printoptions(
#     precision=None,    # 小数点后保留几位
#     threshold=None,    # 控制省略长数组的阈值
#     edgeitems=None,    # 开头和结尾显示的元素个数
#     linewidth=None,    # 每行最多显示多少字符
#     suppress=None      # 是否禁止科学计数法
# )

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [ ]:
Z = np.arange(100)
v = np.random.uniform(0,100)
Index=abs(Z-v).argmin()
print(Z[Index])

41


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [ ]:
Z = np.zeros(10, dtype=[
    ('position', np.dtype([('x', float), ('y', float)])),
    ('color',    np.dtype([('r', float), ('g', float), ('b', float)]))
])
print(Z)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [ ]:
Z = np.random.random((100,2)) 
X,Y = np.atleast_2d(Z[:,0], Z[:,1]) 
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
print(D)

[[0.         0.66744406 0.18473152 ... 0.08171468 0.54762785 0.12332558]
 [0.66744406 0.         0.59305914 ... 0.60788272 0.40403757 0.54868218]
 [0.18473152 0.59305914 0.         ... 0.10996426 0.59590339 0.18957054]
 ...
 [0.08171468 0.60788272 0.10996426 ... 0.         0.53657816 0.10145719]
 [0.54762785 0.40403757 0.59590339 ... 0.53657816 0.         0.43685714]
 [0.12332558 0.54868218 0.18957054 ... 0.10145719 0.43685714 0.        ]]


#### 53. How to convert a float (32 bits) array into an integer (32 bits) array in place?

In [ ]:
Z = (np.random.rand(10)*100).astype(np.float32)
Y = Z.view(np.int32) #重新采用int来解释二进制代码
Y[:] = Z  #触发强制类型转换为int
print(Y)

[27 53 53 38 19 24 78 69 55 26]


#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [ ]:
from io import StringIO

# Fake file
s = StringIO('''1, 2, 3, 4, 5

                6,  ,  , 7, 8

                 ,  , 9,10,11
''')
Z = np.genfromtxt(s, delimiter=",", dtype=int)
print(Z)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [ ]:
Z=np.arange(9).reshape(3,3)
for index,value in np.ndenumerate(Z):
    print(index,value)
for index in np.ndindex(Z.shape):
    print(index)
for index,value in enumerate(Z):  #这个只会打印行
    print(index,value)


(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0)
(0, 1)
(0, 2)
(1, 0)
(1, 1)
(1, 2)
(2, 0)
(2, 1)
(2, 2)
0 [0 1 2]
1 [3 4 5]
2 [6 7 8]


#### 56. Generate a generic 2D Gaussian-like array (★★☆)

In [ ]:
X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0
G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
print(G)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [51]:
n=10
p=3
Z=np.zeros((n,n))
np.put(Z,np.random.choice(range(n*n),p,replace=False),1) #replace=False 不放回
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 58. Subtract the mean of each row of a matrix (★★☆)

In [ ]:
Z=np.random.random((10,10))
Z=Z-Z.mean(axis=1,keepdims=True) #默认是对所有值取平均值
print(Z)


#### 59. How to sort an array by the nth column? (★★☆)

In [54]:
Z=np.random.randint(0,10,(3,3))
print(Z)
print(Z[:,1].argsort())
print(Z[Z[:,1].argsort()])

[[3 6 1]
 [7 1 8]
 [6 1 4]]
[1 2 0]
[[7 1 8]
 [6 1 4]
 [3 6 1]]


#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [60]:
# Author: Warren Weckesser
# null : 0 
Z = np.random.randint(0,3,(3,10))
print((~Z.any(axis=0)).any())

# null : np.nan
Z=np.array([
    [0,1,np.nan],
    [1,2,np.nan],
    [4,5,np.nan]
])
print(np.isnan(Z))
print(np.isnan(Z).all(axis=0))

False
[[False False  True]
 [False False  True]
 [False False  True]]
[False False  True]


#### 61. Find the nearest value from a given value in an array (★★☆)

In [71]:
Z = np.random.uniform(0,1,(10,10))
z=0.5
print(abs(Z-z).argmin())
print(Z.flat[abs(Z-z).argmin()]) #Z.flat
print(Z.flatten()[abs(Z-z).argmin()])

16
0.4997223360688512
0.4997223360688512


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [2]:
A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)
it = np.nditer([A,B,None])
for x,y,z in it: 
    z[...] = x + y
print(it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 63. Create an array class that has a name attribute (★★☆)

In [3]:
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.name = getattr(obj, 'name', "no name")

Z = NamedArray(np.arange(10), "range_10")
print (Z.name)

range_10


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [5]:
Z=np.ones(10)
I=np.random.randint(0,len(Z),20)
Z+=np.bincount(I,minlength=len(Z)) 
print(Z)

[3. 6. 1. 3. 2. 4. 2. 3. 4. 2.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

In [ ]:
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]   
F=np.bincount(I,X)   #统计I中每一个元素的count，并且按照X的权重累加
print(F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

In [ ]:
w, h = 256, 256
I = np.random.randint(0, 4, (h, w, 3)).astype(np.ubyte)
colors = np.unique(I.reshape(-1, 3), axis=0)
n = len(colors)
print(n)

w, h = 256, 256
I = np.random.randint(0,4,(h,w,3), dtype=np.uint8)

# View each pixel as a single 24-bit integer, rather than three 8-bit bytes
I24 = np.dot(I.astype(np.uint32),[1,256,65536])
#I24=R×1+G×256+B×65536
# Count unique colours
n = len(np.unique(I24))
print(n)

64
64


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

In [ ]:
A = np.random.randint(0,10,(3,4,3,4))
sum=A.sum(axis=(-2,-1))
#A.shape == (2, 3, 4, 5)
#A.reshape((2, 3, -1)).shape  # (2, 3, 20)
sum = A.reshape(A.shape[:-2] + (-1,)).sum(axis=-1)   
print(sum)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

In [ ]:
D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print(D_means)

[0.64156591 0.43129904 0.51857206 0.62108324 0.41004171 0.35665418
 0.54107359 0.44154717 0.47911336 0.33957978]


#### 69. How to get the diagonal of a dot product? (★★★)

In [ ]:
# Author: Mathieu Blondel

A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))

# Slow version
np.diag(np.dot(A, B))

# Fast version
np.sum(A * B.T, axis=1)


array([2.08284737, 0.92675252, 1.06496949, 1.33171043, 0.98569618])

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [ ]:
Z = np.array([1,2,3,4,5])
nz = 3
Z0 = np.zeros(len(Z) + (len(Z)-1)*(nz))
Z0[::nz+1] = Z
print(Z0)

#### 71. Consider an array of dimension (5,5,3), how to multiply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extracts a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combination of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)