# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialise.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [ ]:
#%run initialise.py

#### 1. Import the numpy package under the name `np` (★☆☆)

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [ ]:
print(np.__version__)
np.show_config

1.24.4
<module 'numpy.version' from 'f:\\Anaconda\\envs\\env_ML\\lib\\site-packages\\numpy\\version.py'>


<function numpy.__config__.show()>

#### 3. Create a null vector of size 10 (★☆☆)

In [ ]:
Z=np.zeros(10)
print(Z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. How to find the memory size of any array (★☆☆)

In [ ]:
print(Z.itemsize*Z.size)

80


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [ ]:
Z=np.zeros(10)
Z[4]=1
print(Z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [ ]:
Z=np.arange(10,50,dtype=int)
print(Z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [ ]:
Z=np.arange(10,50,dtype=int)
Z=Z[::-1]
print(Z)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [ ]:
print(np.arange(0,9,dtype=int).reshape((3,3)))

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [ ]:
print(np.nonzero([1,2,0,0,4,0]))

(array([0, 1, 4], dtype=int64),)


#### 11. Create a 3x3 identity matrix (★☆☆)

In [ ]:
print(np.eye(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [ ]:
print(np.random.random((3,3,3)))

[[[0.1027986  0.75270611 0.40933338]
  [0.4546016  0.87854761 0.2709707 ]
  [0.96845347 0.79858601 0.19296834]]

 [[0.42454409 0.94643213 0.18169431]
  [0.27804642 0.94369399 0.92914891]
  [0.57823177 0.74586129 0.9936683 ]]

 [[0.3899973  0.92802463 0.58180539]
  [0.88515795 0.73999316 0.39679871]
  [0.526944   0.19671595 0.10208305]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [ ]:
Z=np.random.random((10,10))
print(Z.min(),Z.max())

0.019929792677352065 0.9831989351527307


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [ ]:
print(np.random.random(30).mean())

0.45904095837604747


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [ ]:
Z=np.ones((10,10))
Z[1:-1,1:-1]=0
print(Z)

print('\n')

Z=np.zeros((10,10))
Z[0,:]=1
Z[-1,:]=1
Z[:,0]=1
Z[:,-1]=1
print(Z)


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [ ]:
print(np.pad(np.ones((10,10)),pad_width=1,mode='constant',constant_values=0))

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [ ]:
# nan
# False
# False
# nan
# True
# False

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [ ]:
print(np.diag(1+np.arange(4),-1))

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [ ]:
Z=np.zeros((8,8))
Z[1::2,::2]=1
Z[0::2,1::2]=1
print(Z)


[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [ ]:
print(np.unravel_index(99,(6,7,8)))

(1, 5, 3)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [2]:
Z=np.tile([[1,2],[3,4]],(2,3))
print(Z)

NameError: name 'np' is not defined

#### 22. Normalize a 5x5 random matrix (★☆☆)

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

#### 29. How to round away from zero a float array ? (★☆☆)

#### 30. How to find common values between two arrays? (★☆☆)

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

#### 40. Create a random vector of size 10 and sort it (★★☆)

In [2]:
Z=np.random.random(10)
Z.sort()
print(Z)

[0.15173681 0.27722588 0.35046182 0.6556421  0.66753653 0.76635699
 0.82120226 0.82914984 0.84245772 0.98460944]


#### 41. How to sum a small array faster than np.sum? (★★☆)

In [4]:
Z=np.arange(10)
np.add.reduce(Z)

45

#### 42. Consider two random arrays A and B, check if they are equal (★★☆)

In [6]:
A=np.random.random((10,10))
B=np.random.random((10,10))
# Assuming identical shape of the arrays and a tolerance for the comparison of values
print(np.allclose(A,B))
print(np.array_equal(A,B))

False
False


#### 43. Make an array immutable (read-only) (★★☆)

In [ ]:
Z=np.arange(10)
Z.flags.writeable=False
Z[0]=1

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [8]:
Z=np.random.random((10,2))
X,Y=Z[:,0],Z[:,1]
R=np.sqrt(X**2,Y**2)
T=np.arctan2(Y,X)
print(R)
print(T)

[0.58105196 0.09586445 0.55422247 0.07716065 0.74465079 0.66078524
 0.73325344 0.4321307  0.62248662 0.23912902]
[0.31131558 1.24104959 0.83764364 1.43151335 0.27991075 0.73625223
 0.86050454 1.15591753 0.54433905 1.23547484]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [9]:
Z=np.random.random(10)
print(Z)
Z[np.argmax(Z)]=0
print(Z)

[0.39407702 0.35552052 0.03282239 0.66221331 0.35423924 0.42268493
 0.78600423 0.86366726 0.67577059 0.37715135]
[0.39407702 0.35552052 0.03282239 0.66221331 0.35423924 0.42268493
 0.78600423 0.         0.67577059 0.37715135]


#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [16]:
Z=np.zeros((5,5),[('x',float),('y',float)])
Z['x'],Z['y']=np.meshgrid(np.linspace(0,1,5),np.linspace(0,1,5))
print(Z)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

In [17]:
X=np.arange(8)
Y=X+0.5
C=1.0/(np.subtract.outer(X,Y))
print(np.linalg.det(C))

3638.163637117973


#### 48. Print the minimum and maximum representable values for each numpy scalar type (★★☆)

In [18]:
for type in [np.int8,np.int32,np.int64]:
    print(np.iinfo(type).min)
    print(np.iinfo(type).max)
for type in [np.float32,np.float64]:
    print(np.finfo(type).min)
    print(np.finfo(type).max)
    print(np.finfo(type).eps)
    

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆)

In [ ]:
np.set_printoptions(threshold=float('inf'))
Z=np.ones((50,50))
print(Z)

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [24]:
A=np.arange(100)
B=np.random.uniform(0,100)
index=(np.abs(A-B)).argmin()
print(A[index])

13


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [2]:
Z=np.zeros(10,dtype=[
    ('position',np.dtype([('x',float),('y',float)])),
    ('color',np.dtype([('r',float),('g',float),('b',float)]))
])
print(Z)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [14]:
Z=np.random.random((100,2))
X,Y = np.atleast_2d(Z[:,0], Z[:,1])
print(np.sqrt((X-X.T)**2+(Y-Y.T)**2))


[[0.         0.57907416 0.38530978 ... 0.42660768 0.54795029 0.34211162]
 [0.57907416 0.         0.67560248 ... 0.91108748 0.80861841 0.35526519]
 [0.38530978 0.67560248 0.         ... 0.29865205 0.16782945 0.32061207]
 ...
 [0.42660768 0.91108748 0.29865205 ... 0.         0.33457763 0.56818529]
 [0.54795029 0.80861841 0.16782945 ... 0.33457763 0.         0.46194696]
 [0.34211162 0.35526519 0.32061207 ... 0.56818529 0.46194696 0.        ]]


In [15]:
X,Y = Z[:,0].reshape((1,100)), Z[:,1].reshape((1,100))
print(np.sqrt((X-X.T)**2+(Y-Y.T)**2))

[[0.         0.57907416 0.38530978 ... 0.42660768 0.54795029 0.34211162]
 [0.57907416 0.         0.67560248 ... 0.91108748 0.80861841 0.35526519]
 [0.38530978 0.67560248 0.         ... 0.29865205 0.16782945 0.32061207]
 ...
 [0.42660768 0.91108748 0.29865205 ... 0.         0.33457763 0.56818529]
 [0.54795029 0.80861841 0.16782945 ... 0.33457763 0.         0.46194696]
 [0.34211162 0.35526519 0.32061207 ... 0.56818529 0.46194696 0.        ]]


#### 53. How to convert a float (32 bits) array into an integer (32 bits) array in place?

In [17]:
Z = (np.random.rand(10)*100).astype(np.float32)
Y=Z.view(np.int32)
Y[:]=Z
print(Y)

[42 82 37 59 77 65 10 93 37  9]


#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [18]:
from io import StringIO
s=StringIO('''1, 2, 3, 4, 5

                6,  ,  , 7, 8

                 ,  , 9,10,11
''')
Z=np.genfromtxt(s,delimiter=',',dtype=np.int32)
print(Z)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [21]:
Z=np.arange(9).reshape((3,3))
for index,value in np.ndenumerate(Z):
    print(index,value)
for index in np.ndindex(Z.shape):
    print(index)

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0)
(0, 1)
(0, 2)
(1, 0)
(1, 1)
(1, 2)
(2, 0)
(2, 1)
(2, 2)


#### 56. Generate a generic 2D Gaussian-like array (★★☆)

In [ ]:
X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0
G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
print(G)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [31]:
n = 10
p = 3
Z=np.zeros((n,n))
np.put(Z,np.random.choice(range(n*n),p,replace=False),1)

#### 58. Subtract the mean of each row of a matrix (★★☆)

In [ ]:
Z=np.random.random((10,10))
Z-=np.mean(Z,axis=0,keepdims=True)  #记住keepdims
print(Z)

[[ 0.17993141  0.13537728 -0.12500942 -0.02845153  0.05690521 -0.32742282
  -0.1244894  -0.14951128 -0.13506945  0.3299228 ]
 [-0.31284931  0.40725385 -0.14267766 -0.07420628 -0.28931306 -0.36952683
   0.18645214  0.42954303 -0.0156832   0.31975259]
 [ 0.01530481 -0.369738   -0.00708265 -0.18109599 -0.14565165 -0.25140263
   0.45935877 -0.11306529 -0.35171782 -0.2234007 ]
 [ 0.2034055  -0.35391172  0.14005667  0.09390873  0.4116166   0.02093489
   0.17757127  0.15713335 -0.12230342 -0.24744865]
 [-0.05565604  0.10760648  0.38505256  0.19231857  0.23907272 -0.00729752
   0.08088744  0.47494705  0.02058553  0.29487722]
 [ 0.26094362 -0.03299801  0.03380658  0.18556355 -0.26834829  0.25329279
  -0.23562899 -0.42614827 -0.11181096 -0.40881765]
 [ 0.04972279 -0.14438881  0.15314493  0.41884215  0.18519759  0.17701245
  -0.11733255  0.20081853  0.61542574  0.30540989]
 [ 0.03273412  0.44933542 -0.40151758 -0.12411212 -0.28775802  0.35911626
  -0.19133599 -0.08462074  0.1338253  -0.13454236]


#### 59. How to sort an array by the nth column? (★★☆)

In [28]:
Z=np.random.randint(0,10,(5,5))
print(Z)
n=2
print(Z[Z[:,2].argsort()])

[[7 2 0 0 4]
 [5 5 4 3 3]
 [7 6 2 2 9]
 [1 2 3 6 1]
 [1 8 9 4 5]]
[[7 2 0 0 4]
 [7 6 2 2 9]
 [1 2 3 6 1]
 [5 5 4 3 3]
 [1 8 9 4 5]]


#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [26]:
Z = np.random.randint(0,3,(3,10))
print((~Z.any(axis=0)).any())

Z=np.array([
    [0,1,np.nan],
    [1,2,np.nan],
    [4,5,np.nan]
])
print(np.isnan(Z).all(axis=0))

False
[False False  True]


#### 61. Find the nearest value from a given value in an array (★★☆)

In [24]:
Z=np.random.uniform(0,1,10)
z=0.5
print(Z.flatten()[np.argmin(np.abs(Z-z))])

0.4177963625094159


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [ ]:
A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)
it = np.nditer([A,B,None])
for x,y,z in it: z[...] = x + y  # 相当于 Z[:,:]
print(it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [3]:
Z=np.random.random(10)
B=np.random.randint(0,len(Z),100)
Z+=np.bincount(B,minlength=len(Z))
print(Z)

[ 8.5930365   7.20782148  6.13063427 10.61080514 13.28619472 14.98095383
 13.49812191  9.25933974  9.19596687 11.05804607]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

In [8]:
X = [1,2,3,4,5,6]   # 要累加的值
I = [1,3,9,3,4,1]   # 索引位置
F = np.bincount(I, X)  # 按照 I 中的索引，把 X 中的值累加到 F
print(F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

In [7]:
w,h=256,256
Z=np.random.randint(0,255,(w,h,3)).astype(np.ubyte)
print(len(np.unique(Z.reshape(-1,3),axis=0)))

65398


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

In [ ]:
Z=np.random.random((2,3,4,5))
sum=Z.sum(axis=(-2,-1))

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

In [14]:
D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
D_sum=np.bincount(S,weights=D)
D_count=np.bincount(S)
print(D_sum/D_count)

[0.52225532 0.48326166 0.55447823 0.52352126 0.33665285 0.54137558
 0.62083093 0.63922083 0.48270417 0.5839307 ]


#### 69. How to get the diagonal of a dot product? (★★★)

In [10]:
A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))
print(np.diag(np.dot(A,B)))
print(np.sum(A*B.T,axis=1))

[0.87546488 0.46037062 1.315771   1.00521418 0.46291569]
[0.87546488 0.46037062 1.315771   1.00521418 0.46291569]


#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [12]:
Z=[1, 2, 3, 4, 5]
A=np.zeros(len(Z)+3*(len(Z)-1))
A[::3+1]=Z
print(A)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 71. Consider an array of dimension (5,5,3), how to multiply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extracts a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combination of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)